/**
 * Workflow status values for account deletion requests.
 *
 * Prisma: todo_app_account_deletion_requests.status.
 *
 * These values reflect business lifecycle states used by UI and processing
 * jobs.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EAccountDeletionRequestStatus =
  | "pending_confirmation"
  | "scheduled"
  | "canceled"
  | "completed";
