/**
 * Sortable fields for account deletion requests.
 *
 * Maps to columns on todo_app_account_deletion_requests and supports
 * administrative or user-facing list ordering.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EAccountDeletionRequestOrderBy =
  | "created_at"
  | "scheduled_purge_at"
  | "confirmed_at"
  | "processed_at"
  | "status";
