/**
 * Enumerated activity types for Todo history records.
 *
 * Based on Prisma model todo_app_todo_activities.activity_type and domain
 * events. Represents append-only audit activities recorded for todos, including
 * creation, content updates, completion, reopening, and deletion actions.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EActivityType =
  | "create"
  | "update"
  | "complete"
  | "reopen"
  | "delete";
