/**
 * Type hint for interpreting raw string values stored in configuration/policy
 * tables.
 *
 * Accepted values map to consumer-side parsers and must reflect the intended
 * primitive or semantic type:
 *
 * - String: opaque text
 * - Int: 32/64-bit integer depending on consumer
 * - Double: IEEE 754 double-precision number
 * - Boolean: true/false
 * - Datetime: ISO 8601 date-time (timestamptz) representation
 * - Uri: RFC 3986 URI string
 *
 * Referenced by: todo_app_service_configurations.value_type and
 * todo_app_service_policies.value_type.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EConfigValueType =
  | "string"
  | "int"
  | "double"
  | "boolean"
  | "datetime"
  | "uri";
