/**
 * Sortable field names for todo_app_data_exports listings.
 *
 * Maps to columns on the Prisma model todo_app_data_exports and common list
 * semantics:
 *
 * - Created_at: default recency ordering
 * - Completed_at: completion timestamp when available
 * - Expires_at: link expiry timestamp when available
 * - Status: export workflow status
 * - Export_format: requested format name
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EDataExportOrderBy =
  | "created_at"
  | "completed_at"
  | "expires_at"
  | "status"
  | "export_format";
