/**
 * Supported export formats for personal data export jobs.
 *
 * Prisma stores export_format as a string; this enum documents common formats
 * used by the application. Additional formats may be enabled by policy even if
 * not listed here.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EDataExportFormat = "json" | "csv";
