/**
 * Workflow status values for personal data export jobs.
 *
 * Corresponds to todo_app_data_exports.status in Prisma:
 *
 * - Requested: job was created and awaits processing
 * - Processing: job is currently being prepared
 * - Completed: job finished successfully (download_uri typically available)
 * - Failed: job ended with an error (status_message may describe)
 * - Expired: completed link has expired or record treated as expired by policy
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EDataExportStatus =
  | "requested"
  | "processing"
  | "completed"
  | "failed"
  | "expired";
