/**
 * Sortable fields for Feature Flag listings.
 *
 * These values correspond to columns in the Prisma model todo_app_feature_flags
 * and common administrative sort keys.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EFeatureFlagSortBy =
  | "created_at"
  | "updated_at"
  | "code"
  | "name"
  | "rollout_percentage"
  | "start_at"
  | "end_at";
