/**
 * Sort key for login attempt listings.
 *
 * Maps to columns on Prisma model todo_app_login_attempts:
 *
 * - Occurred_at (event time)
 * - Created_at (record time)
 * - Ip (client address)
 * - Email (attempted email)
 * - Success (boolean outcome)
 *
 * Default is typically occurred_at in descending order.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ELoginAttemptSortBy =
  | "occurred_at"
  | "created_at"
  | "ip"
  | "email"
  | "success";
