/**
 * Sort key options for KPI window snapshots (mv_todo_app_kpi_counters).
 *
 * Values map to Prisma columns:
 *
 * - Window_end: mv_todo_app_kpi_counters.window_end
 * - Window_start: mv_todo_app_kpi_counters.window_start
 * - Created_at: mv_todo_app_kpi_counters.created_at
 * - Updated_at: mv_todo_app_kpi_counters.updated_at
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EOrderByITodoAppKpiCounter =
  | "window_end"
  | "window_start"
  | "created_at"
  | "updated_at";
