/**
 * Scope of rate limiting subject as defined in Prisma model
 * todo_app_rate_limits.scope.
 *
 * - User: per authenticated account (todo_app_users.id)
 * - Ip: per client IP address string
 * - Global: system-wide throttling with no subject-specific dimension
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ERateLimitScope = "user" | "ip" | "global";
