/**
 * Sortable field keys for refresh token listings.
 *
 * Values correspond to columns in Prisma model todo_app_refresh_tokens:
 *
 * - Issued_at: token issuance time
 * - Expires_at: token expiration time
 * - Rotated_at: when this token was superseded by a child token (nullable)
 * - Revoked_at: explicit revocation time (nullable)
 * - Created_at: record creation time
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ERefreshTokenSortBy =
  | "issued_at"
  | "expires_at"
  | "rotated_at"
  | "revoked_at"
  | "created_at";
