/**
 * Sortable columns of todo_app_service_configurations for administrative
 * listing.
 *
 * Values correspond to Prisma columns:
 *
 * - Id: todo_app_service_configurations.id
 * - Namespace: .namespace
 * - Environment: .environment
 * - Key: .key
 * - Value_type: .value_type
 * - Active: .active
 * - Effective_from: .effective_from
 * - Effective_to: .effective_to
 * - Created_at: .created_at
 * - Updated_at: .updated_at
 *
 * Use with ESortOrder to form ORDER BY semantics.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EServiceConfigurationOrderBy =
  | "created_at"
  | "updated_at"
  | "namespace"
  | "environment"
  | "key"
  | "active"
  | "value_type"
  | "effective_from"
  | "effective_to"
  | "id";
