/**
 * Sort direction for ordered query results.
 *
 * Accepted values:
 *
 * - "asc": ascending order
 * - "desc": descending order
 *
 * Used by request types that support sorting, including
 * ITodoAppUserRateCounter.IRequest.order_dir and other list/search DTOs across
 * the service. This is a shared, reusable enum for consistency.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ESortDirection = "asc" | "desc";
