/**
 * Sortable fields for user rate counters.
 *
 * Values correspond to columns in todo_app_user_rate_counters.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ESortTodoAppUserRateCounter =
  | "window_started_at"
  | "window_ends_at"
  | "last_action_at"
  | "blocked_until"
  | "created_at"
  | "updated_at"
  | "count";
