/**
 * Status filter for Todo list views.
 *
 * This enum is used by request types to scope results over the todo_app_todos
 * model. It maps to the Prisma column todo_app_todos.status, which stores
 * business values such as "open" and "completed". The special value "all"
 * indicates that both states should be included (while still excluding records
 * with deleted_at).
 *
 * - All: Include both open and completed items (deleted_at still excluded by
 *   application policy)
 * - Open: Include only items whose status column equals "open"
 * - Completed: Include only items whose status column equals "completed"
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ETodoStatusFilter = "all" | "open" | "completed";
