/**
 * Enumerated export formats for personal data exports.
 *
 * This enumeration constrains the todo_app_data_exports.export_format column to
 * values supported by the API contract. Typical formats for MVP are "json" and
 * "csv". Services validate this field during job creation and persist the
 * chosen value as a raw string in the Prisma table.
 *
 * Prisma reference: todo_app_data_exports.export_format (String).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ETodoAppDataExportFormat = "json" | "csv";
