/**
 * Due-window filter applied to list views of the todo_app_todos table.
 *
 * This filter is evaluated against the Prisma column todo_app_todos.due_at
 * using the requesting user’s timezone context. It never includes deleted rows
 * (deleted_at not null).
 *
 * - Overdue: due_at is earlier than now and status is not "completed"
 * - Today: due_at falls on the requester’s current local calendar date and status
 *   is not "completed"
 * - Future: due_at is later than today in the requester’s timezone and status is
 *   not "completed"
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ETodoDueFilter = "overdue" | "today" | "future";
