import { tags } from "typia";

/**
 * Generic date-time range filter expressed in the user's timezone context.
 *
 * Both properties are optional; when omitted, the corresponding end of the
 * range is unbounded.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDateRange = {
  /**
   * Start of the inclusive time window (ISO 8601, timestamptz).
   *
   * Used to filter records occurring at or after this timestamp.
   */
  from?: (string & tags.Format<"date-time">) | undefined;

  /**
   * End of the inclusive time window (ISO 8601, timestamptz).
   *
   * Used to filter records occurring at or before this timestamp.
   */
  to?: (string & tags.Format<"date-time">) | undefined;
};
