import { EDataExportOrderBy } from "./EDataExportOrderBy";
import { ESortDirection } from "./ESortDirection";

/**
 * Sort directive for ITodoAppDataExport listings. Combines a target column with
 * an optional sort direction.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDataExportSort = {
  /**
   * Field used for ordering results. Values correspond to sortable columns in
   * todo_app_data_exports.
   */
  orderBy: EDataExportOrderBy;

  /**
   * Optional sort direction. If omitted, implementations typically default to
   * descending for timestamp fields.
   */
  direction?: ESortDirection | undefined;
};
