/**
 * Allowed business event types stored in
 * Audits.todo_mvp_audit_events.event_type.
 *
 * Values derived from Prisma schema comments and standardized for MVP
 * analytics.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEAuditEventType =
  | "todo_created"
  | "todo_updated"
  | "todo_completed"
  | "todo_uncompleted"
  | "todo_deleted";
