/**
 * Allowed reason codes for compliance removals stored in
 * Audits.todo_mvp_compliance_removal_records.reason_code.
 *
 * Values derived from Prisma schema commentary examples and standardized for
 * MVP to ensure consistent inputs and analytics.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEComplianceReasonCode =
  | "policy_violation"
  | "legal_request"
  | "user_request_via_admin";
