/**
 * Sort order direction used by request DTOs to constrain input and standardize
 * API behavior.
 *
 * This enumeration is interface-level and independent of Prisma columns; it
 * provides consistent semantics for ascending or descending sort across
 * endpoints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEOrderDirection = "asc" | "desc";
