/**
 * High-level lifecycle filter for sessions used by search/list request DTOs.
 *
 * These values are derived from Auth.todo_mvp_sessions lifecycle columns
 * (revoked_at and expires_at) and are not stored directly in the database. They
 * provide a clear, privacy-preserving query abstraction.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IESessionState = "all" | "active" | "revoked" | "expired";
