/**
 * Allowed sort keys for session listings derived from Auth.todo_mvp_sessions
 * columns.
 *
 * Values map directly to Prisma columns: created_at, last_accessed_at,
 * expires_at, and updated_at. Use with IEOrderDirection to construct
 * predictable, validated sorting rules in request DTOs.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IESessionSortBy =
  | "created_at"
  | "last_accessed_at"
  | "expires_at"
  | "updated_at";
