import { IPage } from "./IPage";
import { ITodoMvpTodo } from "./ITodoMvpTodo";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoMvpTodo = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ITodoMvpTodo[];
};
export namespace IPageITodoMvpTodo {
  /**
   * A page.
   *
   * Collection of records with pagination information.
   */
  export type ISummary = {
    /** Page information. */
    pagination: IPage.IPagination;

    /** List of records. */
    data: ITodoMvpTodo.ISummary[];
  };
}
