import { IPage } from "./IPage";
import { ITodoAppAccountStatusChange } from "./ITodoAppAccountStatusChange";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoAppAccountStatusChange = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ITodoAppAccountStatusChange[];
};
export namespace IPageITodoAppAccountStatusChange {
  /**
   * A page.
   *
   * Collection of records with pagination information.
   */
  export type ISummary = {
    /** Page information. */
    pagination: IPage.IPagination;

    /** List of records. */
    data: ITodoAppAccountStatusChange.ISummary[];
  };
}
