import { IPage } from "./IPage";
import { ITodoMvpComplianceRemovalRecord } from "./ITodoMvpComplianceRemovalRecord";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageITodoMvpComplianceRemovalRecord = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ITodoMvpComplianceRemovalRecord[];
};
