/**
 * Generic object record used as a placeholder for base pagination containers.
 *
 * This named schema satisfies the "Named References Only" rule by avoiding
 * inline anonymous object types. Concrete APIs should not rely on IRecord for
 * final designs; instead, they must use entity-specific schemas (e.g.,
 * ITodoAppTodo.ISummary).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IRecord = {};
