/**
 * Outcome payload for an administrator password change.
 *
 * This DTO communicates security-relevant results without exposing secrets. It
 * reflects policy outcomes such as re-authentication requirements and potential
 * revocation of other sessions recorded in Auth.todo_mvp_sessions, aligning
 * with the Prisma schema lifecycle fields (revoked_at, updated_at,
 * expires_at).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoMvpAdminSecurityResult = {
  /**
   * Indicates whether the administrative credential update completed
   * successfully.
   *
   * True means the password hash in Actors.todo_mvp_admins.password_hash has
   * been replaced. False indicates validation or processing failure.
   */
  success: boolean;

  /**
   * Signals whether the client must re-authenticate after this operation
   * completes.
   *
   * Some policies require re-login following password changes or when session
   * rotation demands new credentials.
   */
  reauth_required: boolean;

  /**
   * Whether other active sessions for this administrator were revoked as part
   * of the password change policy.
   *
   * If true, providers have set Auth.todo_mvp_sessions.revoked_at for other
   * sessions associated with the same todo_mvp_admins.id to reduce risk from
   * stale tokens.
   */
  revoked_other_sessions?: boolean | undefined;
};
