import { tags } from "typia";

import { IAuthorizationToken } from "./IAuthorizationToken";

/**
 * Guest identity entity for anonymous visitors with minimal persisted
 * footprint.
 *
 * Directly corresponds to Actors.todo_mvp_guests in Prisma. The model stores
 * only id, created_at, updated_at (and an internal deleted_at not surfaced in
 * public DTOs) to honor privacy and MVP scope.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoMvpGuest = {
  /**
   * Primary key of the guest identity.
   *
   * Maps to Actors.todo_mvp_guests.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Creation timestamp of the guest identity.
   *
   * Maps to Actors.todo_mvp_guests.created_at.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp of the guest identity.
   *
   * Maps to Actors.todo_mvp_guests.updated_at.
   */
  updated_at: string & tags.Format<"date-time">;
};
export namespace ITodoMvpGuest {
  /**
   * Request body for creating a guest identity and establishing an initial
   * session.
   *
   * Intentionally empty for MVP. Per security rules, audit-derived fields
   * such as ip_address or user_agent are captured by middleware and MUST NOT
   * be client-supplied. The server creates Actors.todo_mvp_guests and the
   * associated Auth.todo_mvp_sessions entries.
   */
  export type ICreate = {};

  /**
   * Authorization response for guest join/refresh operations.
   *
   * Conforms to the IAuthorized pattern: includes the subject id and the
   * IAuthorizationToken bundle. Optionally includes a public guest snapshot
   * corresponding to Actors.todo_mvp_guests.
   */
  export type IAuthorized = {
    /**
     * Unique identifier of the authenticated guest subject.
     *
     * Maps to Actors.todo_mvp_guests.id and identifies the subject for this
     * authorization outcome.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Creation timestamp of the guest identity.
     *
     * Maps to Actors.todo_mvp_guests.created_at.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Last update timestamp of the guest identity.
     *
     * Maps to Actors.todo_mvp_guests.updated_at.
     */
    updated_at: string & tags.Format<"date-time">;

    /** JWT token information for authentication */
    token: IAuthorizationToken;

    /**
     * Optional guest identity snapshot for convenience.
     *
     * Reflects Actors.todo_mvp_guests fields suitable for public return
     * (id, created_at, updated_at).
     */
    guest?: ITodoMvpGuest | undefined;
  };
}
