import { tags } from "typia";

import { IEAccountStatus } from "./IEAccountStatus";
import { IEAdminStatus } from "./IEAdminStatus";
import { IAuthorizationToken } from "./IAuthorizationToken";

/**
 * Administrator entity suitable for administrative views, excluding secret
 * credentials.
 *
 * Security note: The Prisma model includes password_hash for credential
 * storage, but it MUST NOT be exposed by response DTOs. This schema
 * intentionally omits password_hash and any token material.
 *
 * Role context: Admins have limited oversight capabilities in MVP (aggregate
 * insights and account lifecycle) and do not browse or edit member Todo
 * content.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoMvpAdmin = {
  /**
   * Primary key of the administrator record.
   *
   * Reference: Prisma column Actors.todo_mvp_admins.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Administrator’s unique email address.
   *
   * Reference: Prisma column Actors.todo_mvp_admins.email (unique). Do not
   * expose secrets. This is a business-unique identifier for admins.
   */
  email: string & tags.Format<"email">;

  /**
   * Lifecycle status of the administrator account.
   *
   * Reference: Prisma column Actors.todo_mvp_admins.status. The schema
   * commentary suggests values such as "active" or "deactivated" for
   * operational control.
   */
  status: IEAccountStatus;

  /**
   * Timestamp when the admin account was created.
   *
   * Reference: Prisma column Actors.todo_mvp_admins.created_at (Timestamptz).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the admin account was last updated.
   *
   * Reference: Prisma column Actors.todo_mvp_admins.updated_at (Timestamptz).
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp indicating the record is no longer in active use
   * per lifecycle/retention policies.
   *
   * Reference: Prisma column Actors.todo_mvp_admins.deleted_at (Timestamptz,
   * nullable).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoMvpAdmin {
  /**
   * Authorization response DTO for administrator authentication flows
   * (join/login/refresh).
   *
   * Returned after successfully issuing credentials to an admin account.
   * Includes the admin's id and an authorization token bundle. The optional
   * "admin" property provides non-sensitive account metadata.
   */
  export type IAuthorized = {
    /**
     * Unique identifier of the authenticated administrator.
     *
     * Corresponds to Actors.todo_mvp_admins.id (UUID).
     */
    id: string & tags.Format<"uuid">;

    /**
     * Administrator’s unique email address.
     *
     * Reference: Prisma column Actors.todo_mvp_admins.email (unique). Do
     * not expose secrets. This is a business-unique identifier for admins.
     */
    email: string & tags.Format<"email">;

    /**
     * Lifecycle status of the administrator account.
     *
     * Reference: Prisma column Actors.todo_mvp_admins.status. Allowed
     * values in MVP are "active" or "deactivated".
     */
    status: IEAdminStatus;

    /**
     * Timestamp when the admin account was created.
     *
     * Reference: Prisma column Actors.todo_mvp_admins.created_at
     * (Timestamptz).
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when the admin account was last updated.
     *
     * Reference: Prisma column Actors.todo_mvp_admins.updated_at
     * (Timestamptz).
     */
    updated_at: string & tags.Format<"date-time">;

    /**
     * Soft deletion timestamp indicating the record is no longer in active
     * use per lifecycle/retention policies.
     *
     * Reference: Prisma column Actors.todo_mvp_admins.deleted_at
     * (Timestamptz, nullable).
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** JWT token information for authentication */
    token: IAuthorizationToken;

    /**
     * Administrator profile information suitable for client display
     * (excludes secrets like password_hash).
     */
    admin?: ITodoMvpAdmin | undefined;
  };
}
