import { tags } from "typia";

import { ESortDirection } from "./ESortDirection";

/**
 * Account lifecycle status change entity for governance oversight.
 *
 * Represents rows from Prisma model todo_app_account_status_changes, which
 * records point-in-time transitions of a user account’s status. It includes
 * optional administrator attribution, rationale text, and audit timestamps.
 *
 * This entity contains no private Todo content. It exists solely for lifecycle
 * governance and incident investigation.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppAccountStatusChange = {
  /**
   * Primary key of the status transition record.
   *
   * Maps to Prisma column todo_app_account_status_changes.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Subject account identifier undergoing the status change.
   *
   * Maps to Prisma column todo_app_account_status_changes.target_user_id
   * referencing todo_app_users.id.
   */
  target_user_id: string & tags.Format<"uuid">;

  /**
   * Administrator actor responsible for the change when manual.
   *
   * Maps to Prisma column todo_app_account_status_changes.admin_user_id
   * (nullable FK). Null for automated/system-triggered transitions.
   */
  admin_user_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Previous account status value before the transition.
   *
   * Maps to Prisma column todo_app_account_status_changes.previous_status.
   * Examples: "pending_verification", "active", "suspended", "deactivated".
   */
  previous_status: string;

  /**
   * New account status value after the transition.
   *
   * Maps to Prisma column todo_app_account_status_changes.new_status.
   * Examples: "active", "suspended", "deactivated".
   */
  new_status: string;

  /**
   * Business rationale provided for the transition.
   *
   * Maps to Prisma column todo_app_account_status_changes.business_reason
   * (nullable). Human-readable; must not include private Todo content.
   */
  business_reason?: string | null | undefined;

  /**
   * Indicates whether the transition changed the stored status.
   *
   * Maps to Prisma column todo_app_account_status_changes.has_effect
   * (boolean). False for no-op attempts.
   */
  has_effect: boolean;

  /**
   * Record creation timestamp (transition capture time).
   *
   * Maps to Prisma column todo_app_account_status_changes.created_at
   * (timestamptz).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update timestamp (audit enrichment time).
   *
   * Maps to Prisma column todo_app_account_status_changes.updated_at
   * (timestamptz).
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Logical deletion timestamp for retention workflows.
   *
   * Maps to Prisma column todo_app_account_status_changes.deleted_at
   * (nullable timestamptz). Non-null indicates archival; such rows are
   * excluded from normal flows.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppAccountStatusChange {
  /**
   * Order-by fields supported by status change searches.
   *
   * Values correspond to sortable columns in todo_app_account_status_changes.
   * Use with ESortDirection to control sort direction.
   */
  export type EOrderBy = "created_at" | "new_status" | "has_effect";

  /**
   * Account status change search request.
   *
   * This DTO expresses pagination, sorting, and filters over
   * todo_app_account_status_changes for administrative governance. It is
   * read-only and does not mutate account ownership or status by itself.
   *
   * All properties are optional. When null, a property is ignored by the
   * server-side filter builder. Page and limit follow service defaults if
   * omitted.
   */
  export type IRequest = {
    /**
     * Page number for pagination (1-based).
     *
     * Optional. Defaults to 1 when unspecified.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /**
     * Maximum records per page.
     *
     * Optional. Defaults to service policy (commonly 20). Allowed range
     * 1–100.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /**
     * Column to sort by for the result set.
     *
     * Optional. Defaults to created_at when unspecified.
     */
    orderBy?: ITodoAppAccountStatusChange.EOrderBy | null | undefined;

    /**
     * Sort direction to apply with orderBy.
     *
     * Optional. Defaults to "desc" for recent-first lists when unspecified.
     */
    orderDirection?: ESortDirection | null | undefined;

    /**
     * Filter by subject account (todo_app_users.id).
     *
     * Optional. Limits results to status transitions for a specific user.
     */
    target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by administrator actor (todo_app_users.id) responsible for
     * manual transitions.
     *
     * Optional.
     */
    admin_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by previous_status value.
     *
     * Optional. Example values: "pending_verification", "active",
     * "suspended", "deactivated".
     */
    previous_status?: string | null | undefined;

    /**
     * Filter by new_status value.
     *
     * Optional. Example values: "active", "suspended", "deactivated".
     */
    new_status?: string | null | undefined;

    /**
     * Filter by whether the transition had effect.
     *
     * Optional. True for effective transitions; false for no-op attempts.
     */
    has_effect?: boolean | null | undefined;

    /**
     * Start of creation timestamp range filter (inclusive).
     *
     * ISO 8601 date-time.
     */
    created_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * End of creation timestamp range filter (inclusive).
     *
     * ISO 8601 date-time.
     */
    created_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Free-text search over business_reason.
     *
     * Case-insensitive substring search aligned with trigram index on
     * business_reason per Prisma schema.
     */
    q?: string | null | undefined;
  };

  /**
   * Summary view of an account status change for administrative listings.
   *
   * Based on Prisma model todo_app_account_status_changes, this summary
   * captures key fields necessary for governance review and audit
   * dashboards.
   */
  export type ISummary = {
    /**
     * Unique identifier of the status change record.
     *
     * Maps to Prisma todo_app_account_status_changes.id.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Subject user ID whose account status changed.
     *
     * Maps to Prisma todo_app_account_status_changes.target_user_id
     * referencing todo_app_users.id.
     */
    target_user_id: string & tags.Format<"uuid">;

    /**
     * Previous account status before the change.
     *
     * Maps to Prisma todo_app_account_status_changes.previous_status.
     */
    previous_status: string;

    /**
     * New account status after the change.
     *
     * Maps to Prisma todo_app_account_status_changes.new_status.
     */
    new_status: string;

    /**
     * Indicates whether the transition actually changed stored status.
     *
     * Maps to Prisma todo_app_account_status_changes.has_effect.
     */
    has_effect: boolean;

    /**
     * Timestamp when the status change was captured.
     *
     * Maps to Prisma todo_app_account_status_changes.created_at
     * (timestamptz).
     */
    created_at: string & tags.Format<"date-time">;
  };
}
