import { tags } from "typia";

/**
 * Acknowledgment result for verification resend (System Admin flow).
 *
 * When a resend is enqueued, a new todo_app_email_verifications row is created
 * (sent_at, expires_at, token_hash). This response confirms acceptance without
 * revealing account existence, aligning with privacy-preserving behavior
 * described in the schema comments.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSystemAdminEmailVerificationResendResult = {
  /**
   * Indicates whether the resend request has been accepted for processing.
   *
   * Privacy-preserving acknowledgment; does not assert whether a matching
   * user exists.
   */
  acknowledged: boolean;

  /**
   * Timestamp when the verification message was (or will be) sent.
   *
   * Maps to todo_app_email_verifications.sent_at. May be null if the provider
   * does not disclose scheduling details.
   */
  sent_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Expiration timestamp for the newly issued verification token.
   *
   * Maps to todo_app_email_verifications.expires_at. May be null if the
   * provider does not disclose expiry details.
   */
  expires_at?: (string & tags.Format<"date-time">) | null | undefined;
};
