import { tags } from "typia";

import { ESortDirection } from "./ESortDirection";
import { EAccountDeletionRequestOrderBy } from "./EAccountDeletionRequestOrderBy";

/**
 * Account deletion request entity mapped to Prisma model
 * todo_app_account_deletion_requests.
 *
 * This model represents a user-initiated workflow to delete their account and
 * associated personal data. It captures lifecycle timestamps (confirmation,
 * scheduling, processing, cancellation) and request context (IP and user-agent)
 * for governance and audit.
 *
 * Ownership is enforced via todo_app_user_id; request DTOs must never accept
 * this field from clients. System-managed fields (id, created_at, updated_at,
 * deleted_at) are read-only in responses.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppAccountDeletionRequest = {
  /**
   * Primary key.
   *
   * Prisma: todo_app_account_deletion_requests.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Owner user's identifier.
   *
   * Prisma: todo_app_account_deletion_requests.todo_app_user_id →
   * todo_app_users.id.
   *
   * Read-only in API models; not accepted in request types.
   */
  todo_app_user_id: string & tags.Format<"uuid">;

  /**
   * Deletion workflow status (e.g., pending_confirmation, scheduled,
   * canceled, completed).
   *
   * Prisma: todo_app_account_deletion_requests.status.
   */
  status: string;

  /**
   * Optional human-readable reason or note for the deletion request.
   *
   * Prisma: todo_app_account_deletion_requests.reason (nullable).
   */
  reason?: string | null | undefined;

  /**
   * Timestamp when the deletion request was confirmed by the user, if
   * applicable.
   *
   * Prisma: confirmed_at (nullable timestamptz).
   */
  confirmed_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Scheduled start time for purge operations per policy.
   *
   * Prisma: scheduled_purge_at (nullable timestamptz).
   */
  scheduled_purge_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Timestamp when deletion processing completed for the account.
   *
   * Prisma: processed_at (nullable timestamptz).
   */
  processed_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Timestamp when the deletion request was canceled or withdrawn.
   *
   * Prisma: canceled_at (nullable timestamptz).
   */
  canceled_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * IP address captured at request time for traceability.
   *
   * Prisma: request_ip (nullable).
   */
  request_ip?: string | null | undefined;

  /**
   * User agent at request time for traceability.
   *
   * Prisma: request_user_agent (nullable).
   */
  request_user_agent?: string | null | undefined;

  /**
   * Creation timestamp for the deletion request record.
   *
   * Prisma: created_at (timestamptz).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp for the deletion request record.
   *
   * Prisma: updated_at (timestamptz).
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Logical deletion timestamp; when set, the record is excluded from normal
   * flows.
   *
   * Prisma: deleted_at (nullable timestamptz).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppAccountDeletionRequest {
  /**
   * Search, filtering, and pagination parameters for listing account deletion
   * requests.
   *
   * Security: The server must constrain results to the authenticated owner
   * (todo_app_user_id) and ignore any client attempt to scope by user
   * identity.
   */
  export type IRequest = {
    /** Page number to retrieve (min 1). */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Page size (1–100). */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /**
     * Filter by workflow status (e.g., pending_confirmation, scheduled,
     * canceled, completed).
     */
    status?: string | null | undefined;

    /** Filter: created_at from (inclusive). */
    created_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter: created_at to (inclusive). */
    created_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter: scheduled_purge_at from (inclusive). */
    scheduled_purge_at_from?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** Filter: scheduled_purge_at to (inclusive). */
    scheduled_purge_at_to?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** Filter: processed_at from (inclusive). */
    processed_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter: processed_at to (inclusive). */
    processed_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter: canceled_at from (inclusive). */
    canceled_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter: canceled_at to (inclusive). */
    canceled_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Free-text search over reason (policy-dependent). */
    q?: string | null | undefined;

    /** Sort field (e.g., created_at or scheduled_purge_at). */
    order_by?: string | null | undefined;

    /** Sort direction (asc or desc). */
    order_dir?: ESortDirection | null | undefined;
  };

  /**
   * Request body for creating a new account deletion request.
   *
   * Only accepts user-supplied reason. All system/ownership and lifecycle
   * fields are assigned by the server.
   */
  export type ICreate = {
    /**
     * Optional user-provided reason or context for the deletion request.
     *
     * Prisma: todo_app_account_deletion_requests.reason.
     *
     * SECURITY: Server sets ownership (todo_app_user_id), status, and
     * timestamps. Client must NOT provide system fields.
     */
    reason?: string | undefined;
  };

  /**
   * Summary projection of the account deletion request for list views.
   *
   * Contains essential properties (id, status, key timestamps) and omits
   * verbose fields to keep listings compact.
   */
  export type ISummary = {
    /** Primary key of the deletion request. */
    id: string & tags.Format<"uuid">;

    /** Workflow status for quick display. */
    status: string;

    /** Scheduled purge time when applicable; used for timeline displays. */
    scheduled_purge_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Completion time when the deletion has finished. */
    processed_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Creation timestamp for ordering and list views. */
    created_at: string & tags.Format<"date-time">;
  };

  /**
   * Sort directive for account deletion request listings.
   *
   * Nested variant under ITodoAppAccountDeletionRequest to follow naming
   * conventions.
   */
  export type ISort = {
    /**
     * Field used for ordering results.
     *
     * Maps to a column on todo_app_account_deletion_requests.
     */
    orderBy: EAccountDeletionRequestOrderBy;

    /**
     * Optional sort direction. Default typically desc for time-based
     * fields.
     */
    direction?: ESortDirection | undefined;
  };
}
