/**
 * Acknowledgment response for an administrator password reset request.
 *
 * Privacy: Does not reveal whether the email exists in todo_app_users. Aligns
 * with the design of todo_app_password_resets to prevent user enumeration.
 *
 * No secrets (tokens, hashes) are ever returned.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSystemAdminPasswordResetRequestResult = {
  /**
   * True when the password reset request has been accepted for processing.
   *
   * This acknowledgment corresponds to creating a todo_app_password_resets
   * record (email, token_hash, requested_at, expires_at) without disclosing
   * whether a user exists.
   */
  accepted: boolean;

  /**
   * Optional human-readable message for UX guidance.
   *
   * Does not disclose whether the email maps to an account. Content may
   * reflect high-level next steps (e.g., "If an account exists, you'll
   * receive an email with instructions shortly.")
   */
  message?: string | undefined;
};
