import { tags } from "typia";

/**
 * Daily statistics (full entity).
 *
 * Represents a denormalized, read-optimized snapshot for a specific calendar
 * date derived from base sources, as described by the Prisma model
 * mv_todo_app_daily_stats. Includes creation/refresh timestamps for cache
 * introspection and excludes private todo content.
 *
 * Returned by administrative analytics detail endpoints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppDailyStat = {
  /**
   * Unique identifier of the daily statistics row.
   *
   * Prisma: mv_todo_app_daily_stats.id
   */
  id: string & tags.Format<"uuid">;

  /**
   * Calendar day represented as UTC start-of-day timestamp.
   *
   * Prisma: mv_todo_app_daily_stats.stats_date
   */
  stats_date: string & tags.Format<"date-time">;

  /**
   * Number of todos created on stats_date.
   *
   * Prisma: mv_todo_app_daily_stats.todos_created
   */
  todos_created: number & tags.Type<"int32">;

  /**
   * Number of todos completed on stats_date.
   *
   * Prisma: mv_todo_app_daily_stats.todos_completed
   */
  todos_completed: number & tags.Type<"int32">;

  /**
   * Distinct count of active users on stats_date.
   *
   * Prisma: mv_todo_app_daily_stats.active_users
   */
  active_users: number & tags.Type<"int32">;

  /**
   * Ratio of completed to created todos for stats_date.
   *
   * Prisma: mv_todo_app_daily_stats.completion_ratio
   */
  completion_ratio: number;

  /**
   * Timestamp when this MV row was last refreshed from source data.
   *
   * Prisma: mv_todo_app_daily_stats.refreshed_at
   */
  refreshed_at: string & tags.Format<"date-time">;

  /**
   * Materialized view row creation timestamp in cache.
   *
   * Prisma: mv_todo_app_daily_stats.created_at
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Materialized view row last refresh timestamp in cache.
   *
   * Prisma: mv_todo_app_daily_stats.updated_at
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Logical deletion timestamp for the MV row if removed from active view.
   *
   * Prisma: mv_todo_app_daily_stats.deleted_at (nullable).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppDailyStat {
  /**
   * Search and pagination parameters for listing daily statistics from
   * mv_todo_app_daily_stats.
   *
   * Includes date-range filters and page controls; excludes any sensitive
   * identifiers or system-managed timestamps as client inputs.
   */
  export type IRequest = {
    /** Page number (1-based). */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Items per page (1–100). */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /** Lower bound (inclusive) for stats_date (UTC). */
    stats_date_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Upper bound (inclusive) for stats_date (UTC). */
    stats_date_to?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Sort expression, e.g., 'stats_date desc' (default), 'todos_created
     * desc'.
     */
    sort?: string | null | undefined;
  };

  /**
   * Summary projection of a daily statistics row for list views.
   *
   * Derived from mv_todo_app_daily_stats. Contains essential metrics only;
   * omits cache lifecycle timestamps to keep list payloads lean.
   */
  export type ISummary = {
    /**
     * Identifier of the daily statistics row.
     *
     * Prisma: mv_todo_app_daily_stats.id
     */
    id: string & tags.Format<"uuid">;

    /**
     * Calendar date represented as start-of-day UTC timestamp.
     *
     * Prisma: mv_todo_app_daily_stats.stats_date
     */
    stats_date: string & tags.Format<"date-time">;

    /**
     * Number of todos created on stats_date.
     *
     * Prisma: mv_todo_app_daily_stats.todos_created
     */
    todos_created: number & tags.Type<"int32">;

    /**
     * Number of todos completed on stats_date.
     *
     * Prisma: mv_todo_app_daily_stats.todos_completed
     */
    todos_completed: number & tags.Type<"int32">;

    /**
     * Distinct count of active users on stats_date.
     *
     * Prisma: mv_todo_app_daily_stats.active_users
     */
    active_users: number & tags.Type<"int32">;

    /**
     * Completed / Created ratio for stats_date.
     *
     * Prisma: mv_todo_app_daily_stats.completion_ratio
     */
    completion_ratio: number;
  };
}
