import { tags } from "typia";

import { ESortDirection } from "./ESortDirection";

/**
 * Administrative action entity for governance audit.
 *
 * This schema represents rows from Prisma model todo_app_admin_actions, which
 * stores privileged administrative operations performed by system
 * administrators. Properties align directly with the table columns, referencing
 * user actors and optional targets via foreign keys to todo_app_users.
 *
 * The entity contains no private Todo content. Text fields such as reason and
 * notes are intended for human-readable context and must not contain secrets.
 * Timestamps support audit timelines and retention policies.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppAdminAction = {
  /**
   * Primary key of the administrative action.
   *
   * Maps to Prisma column todo_app_admin_actions.id (UUID). This value
   * uniquely identifies a privileged administrative operation captured for
   * governance review.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Administrator actor's user identifier.
   *
   * Maps to Prisma column todo_app_admin_actions.admin_user_id referencing
   * todo_app_users.id. Indicates who performed the privileged action for
   * auditability.
   */
  admin_user_id: string & tags.Format<"uuid">;

  /**
   * Optional target user's identifier affected by the administrative action.
   *
   * Maps to Prisma column todo_app_admin_actions.target_user_id (nullable FK
   * to todo_app_users.id). Null when the action is service-wide or not tied
   * to a specific account.
   */
  target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Administrative action key.
   *
   * Maps to Prisma column todo_app_admin_actions.action. Examples:
   * "suspend_account", "reactivate_account", "revoke_sessions",
   * "update_service_config". Used for governance classification and search.
   */
  action: string;

  /**
   * Business reason provided by the administrator.
   *
   * Maps to Prisma column todo_app_admin_actions.reason (nullable).
   * Human-readable context; must not include private Todo content.
   */
  reason?: string | null | undefined;

  /**
   * Operational notes associated with the action.
   *
   * Maps to Prisma column todo_app_admin_actions.notes (nullable). Free-form
   * admin comments without private Todo text.
   */
  notes?: string | null | undefined;

  /**
   * Outcome of the administrative action.
   *
   * Maps to Prisma column todo_app_admin_actions.success (boolean). True when
   * the operation completed successfully; false otherwise.
   */
  success: boolean;

  /**
   * Optional idempotency token for the admin operation.
   *
   * Maps to Prisma column todo_app_admin_actions.idempotency_key (unique,
   * nullable). Used to guard against accidental duplicate execution.
   */
  idempotency_key?: string | null | undefined;

  /**
   * Record creation timestamp (action capture time).
   *
   * Maps to Prisma column todo_app_admin_actions.created_at (timestamptz).
   * Represents when this audit row was created.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update timestamp.
   *
   * Maps to Prisma column todo_app_admin_actions.updated_at (timestamptz).
   * Typically updated for operational correction or audit enrichment.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Logical deletion timestamp for retention workflows.
   *
   * Maps to Prisma column todo_app_admin_actions.deleted_at (nullable
   * timestamptz). When not null, the record is considered archived and
   * excluded from normal flows.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppAdminAction {
  /**
   * Order-by fields supported by administrative action searches.
   *
   * Values correspond to sortable columns in todo_app_admin_actions. Use with
   * ESortDirection to control sort direction.
   *
   * - Created_at: chronological ordering for recent-first/oldest-first views
   * - Action: lexical ordering by action key
   * - Success: boolean outcome ordering (implementation-defined secondary
   *   sorts)
   */
  export type EOrderBy = "created_at" | "action" | "success";

  /**
   * Administrative action search request.
   *
   * This DTO expresses pagination, sorting, and filters over
   * todo_app_admin_actions for governance and operations consoles. It does
   * not mutate ownership or create records; it only shapes a read query.
   *
   * All properties are optional. When null, a property is ignored by the
   * server-side filter builder. Page and limit follow service defaults if
   * omitted.
   */
  export type IRequest = {
    /**
     * Page number for pagination (1-based).
     *
     * Optional. When null or omitted, the service may use a default of 1.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /**
     * Maximum records per page.
     *
     * Optional. When null or omitted, defaults follow policy (commonly 20).
     * The allowed range is 1–100.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /**
     * Column to sort by for the result set.
     *
     * Optional. Defaults to created_at when unspecified.
     */
    orderBy?: ITodoAppAdminAction.EOrderBy | null | undefined;

    /**
     * Sort direction to apply with orderBy.
     *
     * Optional. Defaults to "desc" for recent-first lists when unspecified.
     */
    orderDirection?: ESortDirection | null | undefined;

    /**
     * Filter by administrator actor (todo_app_users.id).
     *
     * Optional filter limiting results to actions performed by a specific
     * admin.
     */
    admin_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by affected target user (todo_app_users.id).
     *
     * Optional filter limiting results to actions affecting a specific
     * user.
     */
    target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by exact administrative action key.
     *
     * Examples: "suspend_account", "reactivate_account".
     */
    action?: string | null | undefined;

    /**
     * Filter by outcome.
     *
     * True for successful operations; false for failed attempts.
     */
    success?: boolean | null | undefined;

    /**
     * Start of creation timestamp range filter (inclusive).
     *
     * ISO 8601 date-time (UTC or with timezone).
     */
    created_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * End of creation timestamp range filter (inclusive).
     *
     * ISO 8601 date-time (UTC or with timezone).
     */
    created_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Free-text search term applied to reason and/or notes fields.
     *
     * Case-insensitive substring search aligned with GIN trigram indexes on
     * notes and reason per Prisma schema.
     */
    q?: string | null | undefined;
  };

  /**
   * Summary view of an administrative action for list displays.
   *
   * Derived from Prisma model todo_app_admin_actions, selecting essential
   * fields suited for administrative listings and dashboards while avoiding
   * verbose text fields by default.
   */
  export type ISummary = {
    /**
     * Unique identifier of the administrative action.
     *
     * Maps to Prisma todo_app_admin_actions.id.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Administrator actor's user ID who performed the action.
     *
     * Maps to Prisma todo_app_admin_actions.admin_user_id referencing
     * todo_app_users.id.
     */
    admin_user_id: string & tags.Format<"uuid">;

    /**
     * Optional target user's ID affected by the action.
     *
     * Maps to Prisma todo_app_admin_actions.target_user_id (nullable FK).
     */
    target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Administrative action key (e.g., "suspend_account",
     * "reactivate_account").
     *
     * Maps to Prisma todo_app_admin_actions.action.
     */
    action: string;

    /**
     * Outcome of the administrative action.
     *
     * Maps to Prisma todo_app_admin_actions.success.
     */
    success: boolean;

    /**
     * Creation timestamp of the admin action record.
     *
     * Maps to Prisma todo_app_admin_actions.created_at (timestamptz).
     */
    created_at: string & tags.Format<"date-time">;
  };
}
