import { tags } from "typia";

/**
 * Verification result for the System Admin email confirmation flow.
 *
 * This response summarizes the outcome of validating and consuming a token from
 * todo_app_email_verifications (consumed_at) and applying the verification
 * flags on todo_app_users (email_verified, verified_at). The server must never
 * return raw token or token_hash values. This type contains only safe,
 * public-facing fields suitable for clients.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSystemAdminEmailVerificationResult = {
  /**
   * Indicates whether the user's email is now verified.
   *
   * Maps to todo_app_users.email_verified and reflects the authoritative
   * verification state after processing.
   */
  email_verified: boolean;

  /**
   * Timestamp when the user was verified.
   *
   * Maps to todo_app_users.verified_at. Returned as an RFC 3339 date-time
   * string when verification has completed; otherwise null when not
   * applicable or unchanged.
   */
  verified_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Indicates whether the provided token has been marked as used.
   *
   * Maps to todo_app_email_verifications.consumed_at (true when non-null).
   * Ensures single-use semantics for verification tokens.
   */
  token_consumed: boolean;
};
