import { tags } from "typia";

/**
 * Append-only audit trail capturing sensitive operations.
 *
 * This schema models the Prisma table todo_app_audit_logs, which records
 * security-relevant actions with actor/target references, resource context,
 * outcomes, and client metadata. Private todo text is never stored here,
 * aligning with the model comments.
 *
 * Use for governance reviews, incident investigation, and compliance reporting.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppAuditLog = {
  /**
   * Primary key of the audit log entry.
   *
   * Prisma column: todo_app_audit_logs.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Acting user's identifier for attribution and accountability.
   *
   * Prisma column: todo_app_audit_logs.actor_user_id → todo_app_users.id
   * (FK).
   */
  actor_user_id: string & tags.Format<"uuid">;

  /**
   * Optional target user's identifier when the action involves a specific
   * account.
   *
   * Prisma column: todo_app_audit_logs.target_user_id → todo_app_users.id
   * (nullable FK).
   */
  target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Business action identifier (e.g., "login", "logout", "suspend_account",
   * "data_export_request").
   *
   * Prisma column: todo_app_audit_logs.action (text).
   */
  action: string;

  /**
   * Domain resource category or model name associated with the action (e.g.,
   * "todo_app_todos", "todo_app_sessions").
   *
   * Prisma column: todo_app_audit_logs.resource_type (text, nullable).
   */
  resource_type?: string | null | undefined;

  /**
   * Identifier of the resource related to this event when applicable.
   * String-typed to accommodate non-UUID external identifiers.
   *
   * Prisma column: todo_app_audit_logs.resource_id (text, nullable).
   */
  resource_id?: string | null | undefined;

  /**
   * Whether the attempted action succeeded (true) or failed (false).
   *
   * Prisma column: todo_app_audit_logs.success (boolean).
   */
  success: boolean;

  /**
   * Origin IP address captured at the time of the event.
   *
   * Prisma column: todo_app_audit_logs.ip (text, nullable).
   */
  ip?: string | null | undefined;

  /**
   * Client user-agent string captured at the time of the event.
   *
   * Prisma column: todo_app_audit_logs.user_agent (text, nullable).
   */
  user_agent?: string | null | undefined;

  /**
   * Record creation timestamp (event capture time).
   *
   * Prisma column: todo_app_audit_logs.created_at (timestamptz).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update timestamp (operational correction/audit enrichment
   * time).
   *
   * Prisma column: todo_app_audit_logs.updated_at (timestamptz).
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp for retention workflows. Null means
   * active/retained.
   *
   * Prisma column: todo_app_audit_logs.deleted_at (timestamptz, nullable).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppAuditLog {
  /**
   * Request payload for searching and paginating audit logs.
   *
   * This DTO targets the Prisma model todo_app_audit_logs and supports
   * administrative governance: pagination, flexible filters across
   * action/resource/outcome, time windows, and ordering.
   */
  export type IRequest = {
    /** Page number for pagination (1-based). */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Page size limit (1–100). Typical default is 20. */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /**
     * Optional filter for actions performed by a specific actor user
     * (admin-only analytics).
     */
    actor_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Optional filter for actions targeting a specific user (admin-only
     * analytics).
     */
    target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Filter by action identifier (exact or substring per implementation). */
    action?: string | null | undefined;

    /** Filter by resource category/model name. */
    resource_type?: string | null | undefined;

    /** Filter by resource identifier (may be non-UUID). */
    resource_id?: string | null | undefined;

    /**
     * Filter by outcome: true for succeeded actions, false for failed
     * attempts.
     */
    success?: boolean | null | undefined;

    /** Filter by origin IP address (text). */
    ip?: string | null | undefined;

    /**
     * Filter by client user-agent (substring matches permitted by
     * implementation).
     */
    user_agent?: string | null | undefined;

    /** Inclusive lower bound for created_at (ISO 8601). */
    created_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Inclusive upper bound for created_at (ISO 8601). */
    created_to?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Sort key for results. Supported fields: created_at (default), action,
     * success.
     */
    sort_by?: "created_at" | "action" | "success" | null | undefined;

    /** Sort direction for ordering results. */
    sort_dir?: "asc" | "desc" | null | undefined;
  };

  /**
   * Audit log summary for list views.
   *
   * This projection contains only essential, non-sensitive attributes
   * appropriate for administrative listings, derived from the Prisma table
   * todo_app_audit_logs.
   *
   * Use this type for paginated summaries; fetch the full ITodoAppAuditLog
   * for detailed inspection.
   */
  export type ISummary = {
    /**
     * Unique identifier of the audit log entry.
     *
     * Prisma column: todo_app_audit_logs.id (UUID).
     */
    id: string & tags.Format<"uuid">;

    /**
     * Acting user's identifier for attribution and accountability.
     *
     * Prisma column: todo_app_audit_logs.actor_user_id → todo_app_users.id
     * (FK).
     */
    actor_user_id: string & tags.Format<"uuid">;

    /**
     * Optional target user's identifier when the action involves a specific
     * account.
     *
     * Prisma column: todo_app_audit_logs.target_user_id → todo_app_users.id
     * (nullable FK).
     */
    target_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Business action identifier (e.g., "login", "logout",
     * "suspend_account").
     *
     * Prisma column: todo_app_audit_logs.action (text).
     */
    action: string;

    /**
     * Outcome of the action: true on success, false on failure.
     *
     * Prisma column: todo_app_audit_logs.success (boolean).
     */
    success: boolean;

    /**
     * Record creation timestamp (event capture time).
     *
     * Prisma column: todo_app_audit_logs.created_at (timestamptz).
     */
    created_at: string & tags.Format<"date-time">;
  };
}
