import { tags } from "typia";

/**
 * Result of an admin self-logout operation.
 *
 * Summarizes the revocation of the current session using fields aligned with
 * todo_app_session_revocations and todo_app_sessions. Contains no secrets or
 * token values.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSystemAdminLogoutResult = {
  /**
   * Identifier of the revoked session.
   *
   * Maps to todo_app_sessions.id and
   * todo_app_session_revocations.todo_app_session_id.
   */
  session_id: string & tags.Format<"uuid">;

  /**
   * Timestamp when the session was revoked.
   *
   * Maps to todo_app_sessions.revoked_at and
   * todo_app_session_revocations.revoked_at.
   */
  revoked_at: string & tags.Format<"date-time">;

  /**
   * Actor category that performed the revocation (e.g., 'admin', 'user', or
   * 'system').
   *
   * Maps to todo_app_session_revocations.revoked_by.
   */
  revoked_by: string;

  /**
   * Optional reason for revocation.
   *
   * Maps to todo_app_session_revocations.reason.
   */
  reason?: (string & tags.MaxLength<500>) | null | undefined;

  /**
   * Optional acknowledgment or user-facing message indicating the logout
   * outcome.
   */
  message?: string | undefined;
};
