import { tags } from "typia";

import { ETodoAppDataExportFormat } from "./ETodoAppDataExportFormat";

/**
 * Personal data export job entity aligned to Prisma table
 * todo_app_data_exports.
 *
 * This type exposes non-sensitive attributes of an export job, including
 * lifecycle state, format, optional download URI and integrity metadata, and
 * timestamps. Ownership is enforced by the API layer based on authentication
 * (todo_app_user_id) and is not passed from the client. Sensitive credentials
 * or tokens are never included in this entity.
 *
 * Prisma reference: todo_app_data_exports.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppDataExport = {
  /**
   * Unique identifier of the export job.
   *
   * Prisma: todo_app_data_exports.id (UUID primary key).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Workflow status of the export job (e.g., requested, processing,
   * completed, failed, expired).
   *
   * Prisma: todo_app_data_exports.status (String). Values are managed by the
   * system and may evolve per policy; the API treats this as a string label.
   */
  status: string;

  /**
   * Requested output format for the export artifact.
   *
   * Prisma: todo_app_data_exports.export_format (String).
   */
  export_format: ETodoAppDataExportFormat;

  /**
   * Secure download URI when the export is completed; null if not yet
   * available or after expiry.
   *
   * Prisma: todo_app_data_exports.download_uri (String?, URI semantics).
   */
  download_uri?: (string & tags.Format<"uri">) | null | undefined;

  /**
   * Size of the generated archive in bytes when available; null otherwise.
   *
   * Prisma: todo_app_data_exports.file_size_bytes (Int?).
   */
  file_size_bytes?: (number & tags.Type<"int32">) | null | undefined;

  /**
   * Integrity checksum (e.g., SHA-256) of the archive as a hexadecimal
   * string; null when unavailable.
   *
   * Prisma: todo_app_data_exports.checksum (String?).
   */
  checksum?: string | null | undefined;

  /**
   * Optional human-readable message for job state or failure reason; null
   * when not applicable.
   *
   * Prisma: todo_app_data_exports.status_message (String?).
   */
  status_message?: string | null | undefined;

  /**
   * Timestamp when the export finished successfully; null if incomplete.
   *
   * Prisma: todo_app_data_exports.completed_at (Timestamptz?).
   */
  completed_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Time after which the download link is no longer valid; null when not
   * issued.
   *
   * Prisma: todo_app_data_exports.expires_at (Timestamptz?).
   */
  expires_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * IP address captured at the time of the export request; null when not
   * captured.
   *
   * Prisma: todo_app_data_exports.request_ip (String?).
   */
  request_ip?: string | null | undefined;

  /**
   * User agent string captured when the export was requested; null when not
   * captured.
   *
   * Prisma: todo_app_data_exports.request_user_agent (String?).
   */
  request_user_agent?: string | null | undefined;

  /**
   * Record creation timestamp (request time).
   *
   * Prisma: todo_app_data_exports.created_at (Timestamptz).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp of the export job record.
   *
   * Prisma: todo_app_data_exports.updated_at (Timestamptz).
   */
  updated_at: string & tags.Format<"date-time">;
};
export namespace ITodoAppDataExport {
  /**
   * Search/filter request model for listing personal data export jobs.
   *
   * Contains only query parameters; does not accept actor IDs or
   * system-managed fields. Pagination semantics align with IPage containers.
   *
   * Backed by Prisma: todo_app_data_exports.
   */
  export type IRequest = {
    /**
     * Page number (1-based). If null or omitted, service defaults are
     * applied.
     */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Page size (allowed range 1–100). If null or omitted, service defaults
     * apply.
     */
    limit?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Optional status filter (e.g., requested, processing, completed,
     * failed, expired).
     */
    status?: string | null | undefined;

    /** Filter lower bound for created_at (inclusive), RFC 3339. */
    from_created_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter upper bound for created_at (inclusive), RFC 3339. */
    to_created_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter lower bound for completed_at (inclusive), RFC 3339. */
    from_completed_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter upper bound for completed_at (inclusive), RFC 3339. */
    to_completed_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Optional filter by export format. */
    export_format?: ETodoAppDataExportFormat | null | undefined;

    /**
     * Optional case-insensitive substring search (e.g., over
     * status_message). Empty or whitespace-only strings are ignored.
     */
    q?: string | null | undefined;

    /**
     * Sort key: one of created_at, completed_at, expires_at. Defaults to
     * created_at.
     */
    order_by?: string | null | undefined;

    /** Sort direction: asc or desc. Defaults to desc. */
    order_dir?: string | null | undefined;
  };

  /**
   * Creation request for a personal data export job.
   *
   * This request body maps to Prisma table todo_app_data_exports. Only
   * business fields that the client is allowed to set are included
   * (export_format). System-managed fields such as status, download_uri,
   * file_size_bytes, checksum, completed_at, and expires_at are not accepted
   * in the request.
   */
  export type ICreate = {
    /**
     * Requested output format for the data export job.
     *
     * Prisma target: todo_app_data_exports.export_format. The server will
     * validate and persist this value while other lifecycle fields are
     * system-managed.
     */
    export_format: ETodoAppDataExportFormat;
  };

  /**
   * Summary projection of a personal data export job for list/search views.
   *
   * Contains essential display fields and omits larger or sensitive details.
   * Backed by todo_app_data_exports.
   */
  export type ISummary = {
    /**
     * Unique identifier of the export job.
     *
     * Prisma: todo_app_data_exports.id.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Workflow status label for the export job, suitable for list views.
     *
     * Prisma: todo_app_data_exports.status.
     */
    status: string;

    /**
     * Output format of the export artifact.
     *
     * Prisma: todo_app_data_exports.export_format.
     */
    export_format: ETodoAppDataExportFormat;

    /**
     * Completion time for finished jobs; null when not yet completed.
     *
     * Prisma: todo_app_data_exports.completed_at.
     */
    completed_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Download link expiry time when applicable; null if unavailable.
     *
     * Prisma: todo_app_data_exports.expires_at.
     */
    expires_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
