import { tags } from "typia";

/**
 * User Preference entity (1:1 with todo_app_users) controlling timezone,
 * locale, and default page size.
 *
 * Based on Prisma table Actors.todo_app_user_preferences. Ownership is enforced
 * via todo_app_user_id and MUST NOT be accepted from clients. System fields are
 * read-only. Page size follows business constraints 1–100; timezone and locale
 * follow IANA/BCP 47 conventions, respectively.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppUserPreference = {
  /**
   * Primary key of the preferences record (UUID).
   *
   * Prisma: todo_app_user_preferences.id — Primary Key.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Owner user's id (FK to todo_app_users.id). Read-only — server derives
   * from context.
   *
   * Prisma: todo_app_user_preferences.todo_app_user_id — 1:1 with users.
   */
  todo_app_user_id: string & tags.Format<"uuid">;

  /**
   * IANA timezone identifier used to interpret due dates and display times
   * (e.g., "Asia/Seoul").
   *
   * Prisma: todo_app_user_preferences.timezone — String. Business rule: must
   * be a valid IANA tz name.
   */
  timezone: string;

  /**
   * Locale in BCP 47 format controlling language/formatting (e.g., "en-US").
   *
   * Prisma: todo_app_user_preferences.locale — String.
   */
  locale: string;

  /**
   * Default pagination size for lists. Business rule: 1–100 (commonly default
   * 20).
   *
   * Prisma: todo_app_user_preferences.page_size — Integer.
   */
  page_size: number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>;

  /**
   * Creation timestamp of the preferences record.
   *
   * Prisma: todo_app_user_preferences.created_at — timestamptz.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp of the preferences record.
   *
   * Prisma: todo_app_user_preferences.updated_at — timestamptz.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp for lifecycle governance. Null when active.
   *
   * Prisma: todo_app_user_preferences.deleted_at — timestamptz, optional.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppUserPreference {
  /**
   * Create request for user preferences.
   *
   * SECURITY: Ownership and system timestamps are server-managed. Do not
   * accept todo_app_user_id, id, created_at, updated_at, or deleted_at in
   * this request.
   *
   * References Prisma model Actors.todo_app_user_preferences.
   */
  export type ICreate = {
    /**
     * IANA timezone identifier (e.g., "Asia/Seoul").
     *
     * Maps to Actors.todo_app_user_preferences.timezone. Used to interpret
     * due dates and date-time displays for the user.
     */
    timezone: string & tags.MinLength<3> & tags.MaxLength<100>;

    /**
     * BCP 47 language tag (e.g., "en-US").
     *
     * Maps to Actors.todo_app_user_preferences.locale. Controls UI text
     * conventions and formatting.
     */
    locale: string & tags.MinLength<2> & tags.MaxLength<35>;

    /**
     * Default pagination size for lists (1–100).
     *
     * Maps to Actors.todo_app_user_preferences.page_size. Typical default
     * is 20.
     */
    page_size: number &
      tags.Type<"int32"> &
      tags.Minimum<1> &
      tags.Maximum<100>;
  };

  /**
   * Update request for user preferences (partial).
   *
   * All fields are optional. SERVER RULES: Never allow client to set system
   * fields or ownership. The server updates updated_at automatically.
   *
   * References Prisma model Actors.todo_app_user_preferences.
   */
  export type IUpdate = {
    /**
     * IANA timezone identifier (e.g., "Asia/Seoul"). Nullable in request
     * semantics to explicitly clear or reset to defaults when policy
     * permits.
     */
    timezone?:
      | (string & tags.MinLength<3> & tags.MaxLength<100>)
      | null
      | undefined;

    /**
     * BCP 47 language tag (e.g., "en-US"). Nullable in request semantics to
     * explicitly clear or reset to defaults when policy permits.
     */
    locale?:
      | (string & tags.MinLength<2> & tags.MaxLength<35>)
      | null
      | undefined;

    /**
     * Default pagination size for lists (1–100). Nullable to express
     * clearing or deferring to system default when allowed by policy.
     */
    page_size?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;
  };
}
