import { tags } from "typia";

import { ESortDirection } from "./ESortDirection";

/**
 * Authentication session entity aligned with Prisma model todo_app_sessions.
 *
 * Security: The sensitive column session_token is intentionally omitted from
 * this response type and must never be exposed in API responses.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSession = {
  /**
   * Primary key.
   *
   * Prisma: todo_app_sessions.id (UUID).
   */
  id: string & tags.Format<"uuid">;

  /**
   * Owner user's UUID.
   *
   * Prisma FK: todo_app_sessions.todo_app_user_id → todo_app_users.id.
   */
  todo_app_user_id: string & tags.Format<"uuid">;

  /**
   * Client IP observed at session creation or last use.
   *
   * Prisma: ip (nullable).
   */
  ip?: string | null | undefined;

  /**
   * Client user-agent captured for security analytics/device recognition.
   *
   * Prisma: user_agent (nullable).
   */
  user_agent?: string | null | undefined;

  /**
   * Session issuance timestamp.
   *
   * Prisma: issued_at (timestamptz).
   */
  issued_at: string & tags.Format<"date-time">;

  /**
   * Session expiry timestamp.
   *
   * Prisma: expires_at (timestamptz).
   */
  expires_at: string & tags.Format<"date-time">;

  /**
   * Revocation timestamp, if the session has been revoked.
   *
   * Prisma: revoked_at (nullable timestamptz).
   */
  revoked_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Human-readable revocation reason (e.g., user logout, password change).
   *
   * Prisma: revoked_reason (nullable).
   */
  revoked_reason?: string | null | undefined;

  /**
   * Record creation time.
   *
   * Prisma: created_at (timestamptz).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update time.
   *
   * Prisma: updated_at (timestamptz).
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion time used for logical removal.
   *
   * Prisma: deleted_at (nullable timestamptz).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppSession {
  /**
   * Request to revoke other active sessions for the authenticated user
   * (self-service security operation).
   *
   * This DTO never accepts user identifiers or system-managed fields;
   * ownership is derived from authentication. Filters reference Prisma Auth
   * schema columns (todo_app_sessions.*) and record the revocation reason via
   * todo_app_session_revocations.
   */
  export type IRevokeOthers = {
    /**
     * If true, include the current authenticated session in the revocation
     * set.
     *
     * Default behavior is to exclude the current session so the caller
     * remains signed in unless explicitly requested.
     */
    include_current?: boolean | undefined;

    /**
     * Human-readable reason recorded with each session revocation.
     *
     * Persists to todo_app_session_revocations.reason when creating
     * revocation entries (no secrets).
     */
    reason?: string | undefined;

    /**
     * Revoke sessions issued before this timestamp.
     *
     * Filters by todo_app_sessions.issued_at (timestamptz).
     */
    issued_before?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Revoke sessions that expire before this timestamp.
     *
     * Filters by todo_app_sessions.expires_at (timestamptz).
     */
    expires_before?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Optional IP filter to target sessions created from a specific client
     * IP address.
     *
     * Matches against todo_app_sessions.ip (text).
     */
    ip?: string | undefined;

    /**
     * Optional user-agent substring filter to target sessions from specific
     * devices/browsers.
     *
     * Matches against todo_app_sessions.user_agent (text).
     */
    user_agent?: string | undefined;
  };

  /**
   * Sortable column keys for authentication sessions.
   *
   * Backed by Prisma model todo_app_sessions columns:
   *
   * - Issued_at: Session issuance time (timestamptz)
   * - Expires_at: Session expiry time (timestamptz)
   * - Created_at: Record creation time (timestamptz)
   * - Updated_at: Record last update time (timestamptz)
   * - Revoked_at: Revocation time if the session has been revoked (nullable
   *   timestamptz)
   */
  export type EOrderBy =
    | "issued_at"
    | "expires_at"
    | "created_at"
    | "updated_at"
    | "revoked_at";

  /**
   * Derived status filter for sessions in list operations.
   *
   * Semantics (implementation-level):
   *
   * - Active: revoked_at is null and expires_at > now
   * - Expired: expires_at <= now (regardless of revoked_at)
   * - Revoked: revoked_at is not null
   * - All: no status filtering applied
   */
  export type EStatus = "active" | "expired" | "revoked" | "all";

  /**
   * Search/filter request for listing authentication sessions owned by the
   * caller.
   *
   * Targets Prisma model todo_app_sessions. Security note: this request type
   * does not accept actor IDs or system-managed fields.
   */
  export type IRequest = {
    /** Page number (1-based). Default commonly 1. */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Page size limit. Allowed range 1–100; default commonly 20. */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /** Field to sort by. See ITodoAppSession.EOrderBy. */
    orderBy?: ITodoAppSession.EOrderBy | null | undefined;

    /** Sort direction. Defaults to desc when omitted. */
    direction?: ESortDirection | null | undefined;

    /** Derived session status filter (active/expired/revoked/all). */
    status?: ITodoAppSession.EStatus | null | undefined;

    /** Lower bound (inclusive) for issued_at in ISO 8601. */
    issued_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Upper bound (inclusive) for issued_at in ISO 8601. */
    issued_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Lower bound (inclusive) for expires_at in ISO 8601. */
    expires_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Upper bound (inclusive) for expires_at in ISO 8601. */
    expires_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Lower bound (inclusive) for revoked_at in ISO 8601. */
    revoked_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Upper bound (inclusive) for revoked_at in ISO 8601. */
    revoked_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter by client IP (substring or exact match per implementation). */
    ip?: (string & tags.MinLength<1> & tags.MaxLength<100>) | null | undefined;

    /** Filter by user agent string (substring match). */
    user_agent?:
      | (string & tags.MinLength<1> & tags.MaxLength<500>)
      | null
      | undefined;

    /** Include rows with deleted_at set. Default is false (exclude). */
    include_archived?: boolean | null | undefined;
  };

  /**
   * Summary projection of an authentication session suitable for account
   * security pages and administrative overviews.
   *
   * This schema intentionally omits the raw session_token per security best
   * practices described in the Prisma model comments. It presents only safe
   * metadata like issuance/expiry, revocation state, client IP, and user
   * agent.
   */
  export type ISummary = {
    /**
     * Primary key of the authentication session.
     *
     * Mapped from Prisma column todo_app_sessions.id (UUID).
     */
    id: string & tags.Format<"uuid">;

    /**
     * Client IP address (IPv4/IPv6 textual form) observed when the session
     * was established or last used.
     *
     * Mapped from Prisma column todo_app_sessions.ip.
     */
    ip?: string | null | undefined;

    /**
     * Client user agent string captured at session creation for security
     * analytics and device recognition.
     *
     * Mapped from Prisma column todo_app_sessions.user_agent.
     */
    user_agent?: string | null | undefined;

    /**
     * Timestamp when the session was issued.
     *
     * Mapped from Prisma column todo_app_sessions.issued_at (timestamptz).
     */
    issued_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when the session expires.
     *
     * Mapped from Prisma column todo_app_sessions.expires_at (timestamptz).
     */
    expires_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when the session was revoked, if applicable.
     *
     * Mapped from Prisma column todo_app_sessions.revoked_at (timestamptz).
     */
    revoked_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Human-readable reason for revocation, if any (e.g., user logout,
     * password change, admin action).
     *
     * Mapped from Prisma column todo_app_sessions.revoked_reason.
     */
    revoked_reason?: string | null | undefined;

    /**
     * Record creation timestamp.
     *
     * Mapped from Prisma column todo_app_sessions.created_at (timestamptz).
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Record last update timestamp.
     *
     * Mapped from Prisma column todo_app_sessions.updated_at (timestamptz).
     */
    updated_at: string & tags.Format<"date-time">;
  };
}
