import { tags } from "typia";

/**
 * Summary response for system administrator session revocation.
 *
 * Reflects updates in Prisma Auth models: todo_app_sessions,
 * todo_app_session_revocations, and todo_app_refresh_tokens (revoked chains).
 * Never exposes token secrets or password-like values.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSystemAdminSessionRevocationResult = {
  /**
   * Whether the revocation workflow completed without errors across targeted
   * sessions.
   */
  success: boolean;

  /**
   * Number of session rows updated with revoked_at in Auth.todo_app_sessions.
   *
   * Each should have a corresponding Auth.todo_app_session_revocations row
   * (unique per session).
   */
  revoked_sessions_count: number & tags.Type<"int32"> & tags.Minimum<0>;

  /**
   * Optional list of revoked session identifiers (UUIDs) for the caller's
   * reference.
   *
   * Never includes raw session_token or refresh token secret values.
   */
  revoked_session_ids?: (string & tags.Format<"uuid">)[] | undefined;

  /**
   * Number of Auth.todo_app_refresh_tokens rows marked with revoked_at due to
   * session revocation.
   *
   * Used for summary only; secrets are never included.
   */
  revoked_refresh_tokens_count?:
    | (number & tags.Type<"int32"> & tags.Minimum<0>)
    | undefined;

  /**
   * Optional human-readable message explaining the result (e.g., counts or
   * policy notes).
   */
  message?: string | undefined;
};
