import { tags } from "typia";

/**
 * Result payload following a system administrator password change.
 *
 * Does not contain any secret values. May summarize session revocations (Prisma
 * Auth models: todo_app_sessions, todo_app_session_revocations) triggered by
 * the change. Primary credential update targets
 * Actors.todo_app_users.password_hash.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppSystemAdminPasswordChangeResult = {
  /**
   * Indicates whether the password change operation completed successfully.
   *
   * If false, no credential was updated and no session revocations were
   * applied.
   */
  success: boolean;

  /**
   * Whether other active sessions (besides the current one) were revoked as a
   * consequence of the password change.
   *
   * If present and true, related rows in Auth.todo_app_sessions gained
   * revoked_at and a corresponding record in
   * Auth.todo_app_session_revocations may have been inserted.
   */
  revoked_other_sessions?: boolean | undefined;

  /**
   * Total number of sessions revoked by policy during this password change.
   *
   * Counts records updated in Auth.todo_app_sessions (Prisma model) excluding
   * logically deleted rows. Does not expose any token secrets.
   */
  revoked_sessions_count?:
    | (number & tags.Type<"int32"> & tags.Minimum<0>)
    | undefined;

  /**
   * Optional human-readable message describing notable outcomes (e.g.,
   * "Password updated; 2 other sessions revoked").
   */
  message?: string | undefined;
};
