import { tags } from "typia";

import { EOrderDirection } from "./EOrderDirection";

/**
 * Business Event entity mirrored from Prisma model todo_app_business_events.
 *
 * This representation exposes classification, optional actor/target/session
 * references as UUIDs, domain and ingestion timestamps, and optional
 * descriptive metadata such as message, source, ip, and user_agent. Sensitive
 * authentication secrets are never included. Access is restricted to authorized
 * administrative contexts according to service policy.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppBusinessEvent = {
  /**
   * Primary key of the business event record.
   *
   * Maps to todo_app_business_events.id.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Classification reference for this event.
   *
   * Maps to todo_app_business_events.todo_app_event_type_id (FK to
   * todo_app_event_types.id).
   */
  todo_app_event_type_id: string & tags.Format<"uuid">;

  /**
   * Actor user when available.
   *
   * Maps to todo_app_business_events.todo_app_user_id (nullable FK to
   * todo_app_users.id).
   */
  todo_app_user_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Target Todo when applicable.
   *
   * Maps to todo_app_business_events.todo_app_todo_id (nullable FK to
   * todo_app_todos.id).
   */
  todo_app_todo_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Session context when applicable.
   *
   * Maps to todo_app_business_events.todo_app_session_id (nullable FK to
   * todo_app_sessions.id).
   */
  todo_app_session_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Domain timestamp when the event occurred.
   *
   * Maps to todo_app_business_events.occurred_at.
   */
  occurred_at: string & tags.Format<"date-time">;

  /**
   * Optional human-readable message describing the event in business terms.
   *
   * Maps to todo_app_business_events.message.
   */
  message?: string | null | undefined;

  /**
   * Optional emitter or subsystem identifier (e.g., "web", "api", "job").
   *
   * Maps to todo_app_business_events.source.
   */
  source?: string | null | undefined;

  /**
   * Optional external/upstream event identifier for
   * idempotency/deduplication.
   *
   * Maps to todo_app_business_events.external_id.
   */
  external_id?: string | null | undefined;

  /**
   * Optional best-effort client IP captured at event time.
   *
   * Maps to todo_app_business_events.ip.
   */
  ip?: string | null | undefined;

  /**
   * Optional user-agent string captured at event time for diagnostics and
   * analytics.
   *
   * Maps to todo_app_business_events.user_agent.
   */
  user_agent?: string | null | undefined;

  /**
   * Record creation timestamp (ingestion time).
   *
   * Maps to todo_app_business_events.created_at.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update timestamp (system-managed).
   *
   * Maps to todo_app_business_events.updated_at.
   */
  updated_at: string & tags.Format<"date-time">;
};
export namespace ITodoAppBusinessEvent {
  /**
   * Sortable column keys supported by business event listings.
   *
   * - Occurred_at: Domain time when the event actually occurred.
   * - Created_at: Ingestion time when the record was persisted.
   */
  export type ESortKey = "occurred_at" | "created_at";

  /**
   * Search and filtering request for Business Events
   * (todo_app_business_events).
   *
   * The properties map to filterable dimensions and pagination/sorting
   * controls. No database writes occur via this structure. Ownership and
   * role-based access are enforced at the controller/service layers.
   *
   * Important: This request must not include credentials, tokens, or secrets;
   * it strictly contains search criteria.
   */
  export type IRequest = {
    /**
     * Page number for pagination. Unsigned 32-bit integer semantics are
     * expected by business rules.
     *
     * This parameter does not exist in the database; it's an API-level
     * control.
     */
    page?: number | null | undefined;

    /**
     * Maximum number of records per page. Business defaults commonly 20,
     * allowed range 1–100.
     *
     * API-level control, not a database column.
     */
    limit?: number | null | undefined;

    /**
     * Primary sort key for listing. Defaults to occurred_at when not
     * provided.
     */
    sort?: ITodoAppBusinessEvent.ESortKey | undefined;

    /**
     * Sort direction paired with the sort key. Defaults to desc when not
     * provided.
     */
    direction?: EOrderDirection | undefined;

    /**
     * Filter by classification: FK to todo_app_event_types.id.
     *
     * Matches Prisma column
     * todo_app_business_events.todo_app_event_type_id.
     */
    todo_app_event_type_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Filter by actor user: FK to todo_app_users.id.
     *
     * Matches Prisma column todo_app_business_events.todo_app_user_id.
     */
    todo_app_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by target Todo: FK to todo_app_todos.id.
     *
     * Matches Prisma column todo_app_business_events.todo_app_todo_id.
     */
    todo_app_todo_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by session: FK to todo_app_sessions.id.
     *
     * Matches Prisma column todo_app_business_events.todo_app_session_id.
     */
    todo_app_session_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Inclusive lower bound for occurred_at filter (ISO 8601 date-time, UTC
     * or with timezone).
     *
     * Occurs in API only; not a stored column.
     */
    occurred_from?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Inclusive upper bound for occurred_at filter (ISO 8601 date-time, UTC
     * or with timezone).
     *
     * API-only filter; not a stored column.
     */
    occurred_to?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Filter by emitter/source identifier (e.g., "web", "api", "job").
     *
     * Maps to todo_app_business_events.source.
     */
    source?: string | null | undefined;

    /**
     * Filter by IP address (text). May include IPv4 or IPv6 string forms.
     *
     * Maps to todo_app_business_events.ip.
     */
    ip?: string | null | undefined;

    /**
     * Case-insensitive substring search term applied to message.
     *
     * Leverages GIN trigram index on message as declared in Prisma
     * (todo_app_business_events).
     */
    message_q?: string | null | undefined;
  };
}
