import { tags } from "typia";

/**
 * Aggregated metric snapshot (full entity).
 *
 * Represents a historical KPI or metric measured over a fixed time window with
 * an explicit granularity, as defined by the Prisma model
 * todo_app_aggregated_metrics. The entity may also be scoped to a user or event
 * type for dimensional analysis.
 *
 * This object is read-only to clients and is returned by detail endpoints and
 * internal analytics tooling; it excludes any private todo content.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppAggregatedMetric = {
  /**
   * Unique identifier of the aggregated metric snapshot.
   *
   * Prisma: todo_app_aggregated_metrics.id
   */
  id: string & tags.Format<"uuid">;

  /**
   * Optional owner/user dimension for the snapshot.
   *
   * Prisma: todo_app_aggregated_metrics.todo_app_user_id (nullable FK to
   * todo_app_users.id).
   */
  todo_app_user_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Optional event type dimension for the snapshot.
   *
   * Prisma: todo_app_aggregated_metrics.todo_app_event_type_id (nullable FK
   * to todo_app_event_types.id).
   */
  todo_app_event_type_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Business metric key identifying the measurement (e.g., 'todos.created',
   * 'latency.p95').
   *
   * Prisma: todo_app_aggregated_metrics.metric_key
   */
  metric_key: string;

  /**
   * Aggregation granularity of the snapshot (e.g., 'hour', 'day', 'week',
   * 'month').
   *
   * Prisma: todo_app_aggregated_metrics.granularity
   */
  granularity: string;

  /**
   * Inclusive start timestamp (UTC) of the aggregation window.
   *
   * Prisma: todo_app_aggregated_metrics.period_start
   */
  period_start: string & tags.Format<"date-time">;

  /**
   * Exclusive end timestamp (UTC) of the aggregation window.
   *
   * Prisma: todo_app_aggregated_metrics.period_end
   */
  period_end: string & tags.Format<"date-time">;

  /**
   * Aggregated metric value for the specified window.
   *
   * Prisma: todo_app_aggregated_metrics.value (double precision).
   */
  value: number;

  /**
   * Unit of the aggregated value (e.g., 'count', 'ms', 'hours').
   *
   * Prisma: todo_app_aggregated_metrics.unit
   */
  unit: string;

  /**
   * Record creation timestamp.
   *
   * Prisma: todo_app_aggregated_metrics.created_at
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update timestamp.
   *
   * Prisma: todo_app_aggregated_metrics.updated_at
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Logical deletion timestamp used to archive records from normal flows.
   *
   * Prisma: todo_app_aggregated_metrics.deleted_at (nullable).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppAggregatedMetric {
  /**
   * Search and pagination parameters for listing aggregated metric snapshots.
   *
   * This request DTO supports filters aligned to columns in
   * todo_app_aggregated_metrics and standard pagination controls. It
   * intentionally excludes ownership actor IDs as inputs to mutable
   * operations and any system-managed timestamps as client-provided values,
   * satisfying security constraints.
   */
  export type IRequest = {
    /**
     * Page number for pagination (1-based). Defaults to service policy when
     * null or omitted.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /**
     * Maximum items per page (1–100). Defaults per service policy when null
     * or omitted.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | null
      | undefined;

    /**
     * Filter by metric key (e.g., 'todos.created'). Case sensitivity per
     * implementation.
     */
    metric_key?: string | null | undefined;

    /** Filter by aggregation granularity (e.g., 'day', 'week'). */
    granularity?: string | null | undefined;

    /** Lower bound (inclusive) for period_start. */
    period_start_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Upper bound (inclusive) for period_start. */
    period_start_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Lower bound (inclusive) for period_end. */
    period_end_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Upper bound (inclusive) for period_end. */
    period_end_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter by owner/user dimension when available. */
    todo_app_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Filter by event type dimension when available. */
    todo_app_event_type_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Sort key with optional direction, e.g., 'period_start desc',
     * 'created_at desc'.
     *
     * Supported fields commonly include period_start, period_end,
     * created_at.
     */
    sort?: string | null | undefined;
  };

  /**
   * Aggregated metric snapshot summary.
   *
   * This schema summarizes historical KPI snapshots from
   * todo_app_aggregated_metrics, including metric key, granularity, window,
   * value, and unit. Optional dimensions scope the metric to a user or event
   * type as defined in the Prisma model.
   *
   * Intended for list and dashboard overviews; it avoids private todo content
   * and focuses on numerical indicators and timestamps.
   */
  export type ISummary = {
    /**
     * Primary key of the aggregated metric snapshot.
     *
     * Maps to todo_app_aggregated_metrics.id (UUID).
     */
    id: string & tags.Format<"uuid">;

    /**
     * Business metric identifier (e.g., 'todos.created', 'todos.completed',
     * 'latency.p95').
     *
     * Maps to todo_app_aggregated_metrics.metric_key.
     */
    metric_key: string;

    /**
     * Aggregation granularity for the snapshot such as 'hour', 'day',
     * 'week', or 'month'.
     *
     * Maps to todo_app_aggregated_metrics.granularity.
     */
    granularity: string;

    /**
     * Inclusive start timestamp for the aggregation window (UTC).
     *
     * Maps to todo_app_aggregated_metrics.period_start (timestamptz).
     */
    period_start: string & tags.Format<"date-time">;

    /**
     * Exclusive end timestamp for the aggregation window (UTC).
     *
     * Maps to todo_app_aggregated_metrics.period_end (timestamptz).
     */
    period_end: string & tags.Format<"date-time">;

    /**
     * Aggregated numeric value for the metric within the window.
     *
     * Maps to todo_app_aggregated_metrics.value (double precision).
     */
    value: number;

    /**
     * Measurement unit of the value (e.g., 'count', 'ms', 'hours').
     *
     * Maps to todo_app_aggregated_metrics.unit.
     */
    unit: string;

    /**
     * Optional owner dimension for the snapshot (user-specific view).
     *
     * Maps to todo_app_aggregated_metrics.todo_app_user_id; nullable.
     */
    todo_app_user_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Optional event type dimension for the snapshot.
     *
     * Maps to todo_app_aggregated_metrics.todo_app_event_type_id; nullable.
     */
    todo_app_event_type_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Snapshot record creation timestamp.
     *
     * Maps to todo_app_aggregated_metrics.created_at (timestamptz).
     */
    created_at: string & tags.Format<"date-time">;
  };
}
